-- FarmSync Vegetable Seed Data
-- Steps stored as pipe-separated "Title: Detail" pairs
-- Run: docker exec -i farming-postgres-1 psql -U postgres -d farmsync < backend/src/database/seed.sql

INSERT INTO vegetables (
  name, scientific_name, description, difficulty_level,
  days_to_harvest, spacing_cm, min_temp_celsius, max_temp_celsius, optimal_temp_celsius,
  water_frequency_days, sunlight_hours, soil_type, ph_min, ph_max,
  season, climate_zones, can_greenhouse, yields_per_plant,
  planting_tips, care_tips, pest_diseases, companion_plants
) VALUES

-- ─── WESTERN VEGETABLES ───────────────────────────────────────────────────────

('Tomato', 'Solanum lycopersicum',
 'One of the most popular home garden vegetables. Warm-season crop producing juicy, nutrient-rich fruit in endless varieties.',
 'intermediate', 75, 60, 10, 35, 24, 7, 8, 'Sandy loam, well-draining', 6.2, 6.8,
 'summer',
 ARRAY['Temperate','Subtropical','Mediterranean / Oceanic','Humid Continental','Temperate Continental'],
 true, 4.5,
 $$Choose a sunny location: Pick a spot with 8+ hours of direct sun — tomatoes need full sun for fruit development|Prepare rich soil: Dig 30cm deep and mix in 3-4 inches of compost; tomatoes are heavy feeders and reward good soil prep|Plant deep for strong roots: Bury 2/3 of the seedling stem — tomatoes form roots along the buried stem, creating a stronger plant|Set up support before planting: Install cage or stake before putting plants in ground to avoid disturbing roots later|Space 60cm apart: Crowded tomatoes get poor airflow and more disease; give each plant room to breathe$$,
 $$Water deeply once a week: Give 2-3 litres per plant, soaking 15cm deep — shallow watering causes shallow roots|Feed every 2 weeks: Use a balanced fertiliser once flowers appear; switch to low-nitrogen once fruit sets|Prune suckers on indeterminate types: Remove shoots growing between stem and branch — this focuses energy into fruit|Mulch 8cm around base: Keeps soil moisture even, prevents soil splash (which spreads disease), and regulates temperature|Watch for blossom end rot: Dark spot on bottom of fruit means inconsistent watering or calcium shortage — water more evenly$$,
 $$Tomato hornworm: Large green caterpillar eating leaves; hand-pick or use Bacillus thuringiensis (Bt) spray|Aphids: Tiny clusters under leaves; blast off with water or spray neem oil weekly|Early blight: Dark spots with yellow rings on lower leaves; remove affected leaves and improve airflow|Late blight: Dark water-soaked patches spreading fast; remove infected parts immediately and avoid overhead watering|Blossom drop: Flowers fall without setting fruit — usually too hot (above 35°C) or too cold; ensure consistent watering$$,
 ARRAY['Basil','Marigold','Garlic','Chives','Dill']),

('Lettuce', 'Lactuca sativa',
 'Fast-growing cool-season leaf vegetable. Perfect for beginners — harvest in as little as 30 days. Grows well in containers and raised beds.',
 'novice', 50, 20, 4, 24, 16, 3, 6, 'Fertile, well-draining', 6.0, 7.0,
 'spring',
 ARRAY['Temperate','Mediterranean / Oceanic','Humid Continental','Temperate Continental','Subtropical'],
 true, 0.3,
 $$Sow seeds in cool weather: Plant when daytime temps are 15-18°C — lettuce bolts (goes bitter and to seed) in heat|Press seeds into surface: Lettuce seeds need light to germinate; barely cover with 3mm of soil and firm gently|Sow in rows 30cm apart: Thin seedlings to 20cm spacing once they have 2 true leaves — use thinnings as baby salad|Water gently at soil level: Seeds and seedlings wash away easily; use a fine rose watering can or drip irrigation|Succession plant every 2 weeks: Sow a fresh row every 2 weeks for continuous harvest rather than a glut$$,
 $$Keep soil consistently moist: Check every 2 days; lettuce roots are shallow and dry out quickly|Mulch between plants: Keeps soil cool and moist — essential for preventing bolting in warmer spells|Harvest outer leaves first: Take the oldest outer leaves and the plant keeps producing; never strip the centre|Shade in warm weather: Drape with 30% shade cloth when temps exceed 22°C to prevent bolting|Watch for slugs at night: They shred leaves overnight; use copper tape around beds or set beer traps$$,
 $$Aphids: Small green/black clusters under leaves; wash off with water or use insecticidal soap|Slugs and snails: Irregular holes in leaves, slime trail present; use iron phosphate pellets or hand-pick at dusk|Downy mildew: Yellow patches on top of leaves, white fuzz below; improve airflow and avoid wetting foliage|Bolting: Plant shoots up and leaves taste bitter — caused by heat or long days; harvest immediately and resow$$,
 ARRAY['Chives','Garlic','Dill','Marigold','Radish']),

('Carrot', 'Daucus carota',
 'Root vegetable requiring loose, deep soil. Patient growers are rewarded with sweet, crunchy roots rich in beta-carotene.',
 'intermediate', 70, 7, 7, 27, 18, 7, 8, 'Sandy loam, deep and loose', 6.0, 6.8,
 'spring',
 ARRAY['Temperate','Mediterranean / Oceanic','Humid Continental','Temperate Continental'],
 false, 0.15,
 $$Prepare deep, rock-free soil: Loosen soil to 30cm depth and remove all stones — obstructions cause forked, misshapen roots|Sow seeds thinly: Scatter seeds 2cm apart in rows 30cm apart; cover with just 6mm of fine soil|Keep seedbed moist until germination: Seeds take 7-21 days; cover with damp cloth or board and check daily|Thin to 7cm apart: Once seedlings are 5cm tall, thin without pulling (use scissors) — disturbing soil dislodges neighbours|Mark rows clearly: Carrots are slow to emerge; mark rows so you don't accidentally dig them up$$,
 $$Water 2-3cm per week consistently: Irregular watering causes splitting; even moisture is key|Exclude light from shoulders: Earth up or mulch around the base — green shoulders taste bitter|Weed carefully: Carrots compete poorly with weeds; hand-weed close to plants to avoid disturbing roots|Fertilise with low-nitrogen feed: Too much nitrogen grows leafy tops and forked roots; use a root vegetable fertiliser|Harvest by loosening soil first: Ease a fork in 10cm away and lever up rather than pulling by tops$$,
 $$Carrot fly: White maggots tunnel through roots; cover with fine mesh immediately after sowing|Aphids: Wilting and leaf curl; spray with water or insecticidal soap|Forked roots: Caused by stony soil or fresh manure; always prepare soil well before sowing|Green shoulders: Roots exposed to light turn bitter and green; hill up soil or mulch around tops$$,
 ARRAY['Onion','Leek','Rosemary','Sage','Tomato']),

('Bell Pepper', 'Capsicum annuum',
 'Sweet, crunchy warm-season vegetable. Takes time but rewards patient growers with colourful fruit high in vitamin C. Excellent in containers.',
 'intermediate', 80, 45, 16, 35, 24, 4, 8, 'Fertile, well-draining loam', 6.0, 6.8,
 'summer',
 ARRAY['Temperate','Subtropical','Mediterranean / Oceanic','Humid Continental'],
 true, 1.5,
 $$Start seeds 8-10 weeks before last frost: Peppers need a long growing season — start indoors in seed trays at 27°C|Harden off for 10 days before transplanting: Gradually expose seedlings to outdoor conditions to prevent transplant shock|Transplant when soil reaches 18°C: Cold soil stunts peppers badly; wait until conditions are reliably warm|Plant at same depth as pot: Unlike tomatoes, peppers should not be buried deep|Space 45cm apart: Good spacing prevents disease and allows pollinators to access all flowers$$,
 $$Water every 3-4 days consistently: Peppers are sensitive to irregular watering which causes blossom drop and fruit problems|Support plants with stakes: Fruit-laden branches snap easily in wind; stake when 30cm tall|Feed with potassium-rich fertiliser: Once flowering starts, switch from balanced feed to high-K formula for better fruit set|Avoid high nitrogen: Too much nitrogen causes leafy, unproductive plants with few peppers|Harvest green or wait for colour: Green peppers are fully mature; waiting 2-3 more weeks gives red/yellow/orange colour$$,
 $$Aphids: Cluster under leaves and on new growth; spray with neem oil or insecticidal soap|Blossom drop: Flowers fall without setting — caused by temps above 35°C or below 16°C; ensure stable warm conditions|Bacterial leaf spot: Dark water-soaked spots on leaves; avoid overhead watering and remove affected leaves|Blossom end rot: Dark leathery patch on fruit bottom; caused by calcium deficiency from inconsistent watering$$,
 ARRAY['Basil','Marigold','Carrot','Onion','Tomato']),

('Cucumber', 'Cucumis sativus',
 'Fast-growing warm-season vine. Produces prolifically once established. Grows vertically on a trellis to save space and improve fruit quality.',
 'novice', 60, 30, 18, 35, 27, 5, 7, 'Moist, well-draining', 6.5, 7.0,
 'summer',
 ARRAY['Temperate','Subtropical','Mediterranean / Oceanic','Humid Continental','Tropical'],
 true, 8.0,
 $$Wait until soil is 18°C+: Cucumbers planted in cold soil fail to thrive; use a soil thermometer to check|Set up trellis before sowing: A 150cm trellis saves space and keeps fruit clean and straight|Sow 2-3 seeds per spot, 2.5cm deep: Thin to strongest seedling once 10cm tall|Water soil, not leaves: Wet foliage causes mildew; use drip irrigation or water at the base only|Warm the soil with black plastic mulch: Laying black plastic 2 weeks before planting dramatically speeds growth$$,
 $$Water deeply twice a week: Cucumbers are 95% water — consistent moisture is essential for non-bitter fruit|Feed with balanced liquid fertiliser every 2 weeks: Start feeding when first flowers appear|Train vines up trellis regularly: Guide tendrils weekly to prevent tangled, shaded growth|Harvest before fruit yellows: Pick every 2-3 days once ready — leaving overripe fruit stops production|Pollination: If fruit is small and yellowing, hand-pollinate by transferring pollen from male to female flowers with a small brush$$,
 $$Powdery mildew: White coating on leaves; improve airflow and avoid wetting leaves — very common in humid conditions|Cucumber beetle: Yellow/black striped beetle chewing leaves and spreading wilt; use row covers early in season|Aphids: Colonies on new growth; spray with water or neem oil|Bitter fruit: Caused by heat stress or inconsistent watering; keep moisture even and shade during extreme heat$$,
 ARRAY['Radish','Nasturtium','Dill','Basil','Sunflower']),

('Zucchini', 'Cucurbita pepo',
 'Extremely productive summer squash. One or two plants feed a family. Fast-growing with large leaves — needs space but rewards are huge.',
 'novice', 55, 90, 14, 38, 24, 7, 7, 'Fertile, well-draining', 6.0, 7.5,
 'summer',
 ARRAY['Temperate','Subtropical','Mediterranean / Oceanic','Humid Continental','Tropical'],
 true, 12.0,
 $$Plant after all frost risk has passed: One cold night kills zucchini; wait until reliably warm|Choose a large, sunny spot: Each plant spreads 90-120cm; plan space accordingly|Sow 3 seeds per hole, 2.5cm deep: Plant in a slight mound for good drainage; thin to strongest plant|Water in well after planting: Soak the planting area thoroughly and mulch immediately|Plant 2-3 plants for good pollination: Zucchinis need male and female flowers open at the same time for fruit set$$,
 $$Water at the base, never the leaves: Wet foliage is the main cause of powdery mildew — water slowly at ground level|Check for fruit daily once plants flower: Zucchini grows incredibly fast; harvest at 15-20cm for best taste|Hand pollinate if fruit fails to set: Take a male flower (thin stem) and brush inside a female flower (has small fruit at base)|Remove any yellowing leaves: Improves airflow and keeps the plant productive longer|Feed monthly with balanced fertiliser: These are hungry plants — feed regularly for sustained production$$,
 $$Powdery mildew: White dusty coating on leaves — very common; improve air circulation and remove badly affected leaves|Squash vine borer: Wilting despite watering; larvae inside stem — cut out and destroy infected sections|Cucumber beetle: Chews leaves and flowers; use row covers on young plants|Poor fruit set: Too few pollinators or only one gender of flowers open; hand pollinate in morning$$,
 ARRAY['Nasturtium','Dill','Borage','Marigold','Corn']),

('Green Beans', 'Phaseolus vulgaris',
 'One of the easiest vegetables to grow. Bush varieties need no support; pole varieties maximise yield in small spaces. Great first crop for beginners.',
 'novice', 55, 15, 16, 32, 22, 5, 8, 'Fertile, well-draining', 6.0, 7.0,
 'summer',
 ARRAY['Temperate','Subtropical','Mediterranean / Oceanic','Humid Continental','Temperate Continental'],
 false, 0.5,
 $$Sow directly after last frost: Beans hate transplanting — sow straight into final position when soil is 16°C+|Sow 4cm deep, 15cm apart: Plant in double rows 30cm apart for easier picking|Set up poles before sowing pole varieties: Install 180cm stakes in a teepee or row before seeds germinate|Do not fertilise with nitrogen: Beans fix their own nitrogen — extra nitrogen grows leaves, not pods|Water in after sowing and keep moist until germination: Germination takes 5-10 days$$,
 $$Water consistently — 2-3cm per week: Irregular watering causes misshapen pods and poor yield|Mulch after germination: Conserves moisture and suppresses weeds which beans compete with poorly|Pick pods when firm and before seeds swell: Older pods are tough and stringy; harvesting frequently encourages more production|Do not hoe close to plants: Beans have shallow roots that are easily damaged by cultivation|Leave a few plants to dry for seed: Mature dry pods give you seed for next year$$,
 $$Aphids: Cluster on growing tips; pinch off heavily infested tips or spray with water|Bean beetle: Black larvae skeletonise leaves; hand-pick or use Bt spray|Halo blight: Water-soaked spots with yellow halo on leaves; use disease-free seed and avoid overhead watering|Root rot: Sudden wilting from soggy soil; ensure good drainage before planting$$,
 ARRAY['Carrot','Cucumber','Squash','Marigold','Borage']),

('Spinach', 'Spinacia oleracea',
 'Super-nutritious cool-season green. Fast to harvest, tolerates light frost, and grows well in containers and raised beds.',
 'novice', 40, 12, 4, 24, 15, 3, 5, 'Fertile, moist, well-draining', 6.5, 7.0,
 'spring',
 ARRAY['Temperate','Mediterranean / Oceanic','Humid Continental','Temperate Continental'],
 true, 0.2,
 $$Sow in cool conditions only: Spinach bolts (goes to seed) quickly above 24°C — sow in early spring or autumn|Sow 1.2cm deep in rows 30cm apart: Thin to 12cm spacing once seedlings have 2 true leaves|Keep seedbed moist during germination: Takes 7-14 days; cover with damp fabric to retain moisture|Prepare soil with plenty of compost: Spinach is a nitrogen-hungry crop that loves rich, moisture-retaining soil|Stagger sowings every 2-3 weeks: For continuous harvest through the cool season$$,
 $$Water every 2-3 days: Never let spinach dry out — drought causes premature bolting|Harvest outer leaves regularly: Pick outer leaves and the plant keeps producing for weeks|Provide shade in warming weather: A 30% shade cloth can extend the season by several weeks|Watch for bolting: As soon as the plant sends up a central stalk, harvest everything immediately before leaves become bitter|Mulch between rows: Keeps soil cool and moist — critical in spring as temperatures rise$$,
 $$Leaf miner: White squiggly trails inside leaves; remove affected leaves; use fine mesh to prevent the fly laying eggs|Aphids: Colonies under leaves; blast off with water or use insecticidal soap|Downy mildew: Yellow patches on top of leaf, white fuzz beneath; improve airflow, sow resistant varieties|Bolting: Plant goes to seed prematurely due to heat or long days; harvest immediately$$,
 ARRAY['Strawberry','Garlic','Pea','Radish','Onion']),

-- ─── INDIAN VEGETABLES ────────────────────────────────────────────────────────

('Bitter Gourd', 'Momordica charantia',
 'Popular in Indian, Chinese and Southeast Asian cooking. Thrives in hot, humid conditions. Requires a trellis. The distinctive bitter taste is valued for its health benefits.',
 'intermediate', 55, 120, 25, 40, 30, 3, 8, 'Loamy, well-draining', 6.0, 6.7,
 'summer',
 ARRAY['Tropical','Subtropical'],
 true, 3.0,
 $$Soak seeds overnight before sowing: Hard seed coat prevents germination; soaking speeds sprouting to 3-5 days|Sow 2 seeds per hole, 2cm deep: Plant at base of a 180cm trellis or fence; remove weaker seedling after germination|Wait for soil to be 25°C+: Bitter gourd demands warmth; cold soil causes failure|Space plants 120cm apart along trellis: Vines spread widely and need room to climb and get airflow|Train vines up support from day one: Guide tendrils weekly to establish climbing habit$$,
 $$Water every 2-3 days in hot weather: Bitter gourd is thirsty — soil should never fully dry out|Feed with balanced fertiliser every 3 weeks: Apply once vines reach 30cm; avoid high nitrogen after flowering begins|Hand-pollinate for better yields: Brush pollen from male flowers (thin stem) into female flowers (mini bitter gourd at base) each morning|Harvest young for mild flavour: Pick when 10-15cm long and skin is still firm-green; older fruit becomes very bitter|Pinch lateral shoots at 5 nodes to encourage branching and more female flowers$$,
 $$Fruit fly: Maggots inside fruit; use fruit fly traps and pick and destroy fallen fruit daily|Powdery mildew: White powder on leaves in humid conditions; improve airflow and remove affected leaves|Aphids: Colonies on new growth; spray with neem oil — effective and safe for food crops|Mosaic virus: Mottled, distorted leaves; remove infected plants immediately and control aphid carriers$$,
 ARRAY['Basil','Marigold','Onion','Garlic']),

('Okra', 'Abelmoschus esculentus',
 'Heat-loving vegetable popular across India, Africa and the southern US. Grows tall and produces continuously once established. Rich in fibre and vitamins.',
 'novice', 60, 30, 22, 40, 30, 5, 8, 'Loamy, well-draining', 6.0, 6.8,
 'summer',
 ARRAY['Tropical','Subtropical'],
 false, 2.0,
 $$Sow directly when soil is warm: Okra needs soil above 22°C to germinate; does not transplant well|Soak seeds in water for 12-24 hours before planting: Speeds germination significantly|Sow 2-3 seeds per hole, 2cm deep, 30cm apart: Thin to 1 plant per position after germination|Sow in full sun only: Okra produces poorly in any shade|Ridge soil up around base when 20cm tall: This supports the tall plant and encourages side roots$$,
 $$Water every 4-5 days: Deep watering encourages deep roots and drought resilience|Harvest pods every 2-3 days without fail: Pods become tough and fibrous very quickly — pick at 8-10cm for best texture|Feed monthly with balanced fertiliser: Okra benefits from steady nutrition during the long growing season|Wear gloves when harvesting: The plant has fine spines that irritate skin|Leave a few late-season pods to mature fully for next year seed saving$$,
 $$Aphids: Common on young plants; spray with neem oil or water|Root-knot nematode: Stunted growth with knotted roots; rotate crops and add marigolds to the bed|Fusarium wilt: Yellowing and wilting from the base; no cure — remove plant and do not replant okra in that spot for 2 years|Pod borer: Caterpillars inside pods; pick and destroy affected pods, use Bt spray$$,
 ARRAY['Pepper','Basil','Sunflower','Marigold']),

('Eggplant', 'Solanum melongena',
 'Known as brinjal across South Asia and Africa. Long season but generous producer. A staple of Indian, Mediterranean and Asian cooking.',
 'intermediate', 80, 60, 20, 38, 27, 4, 8, 'Rich, well-draining loam', 5.5, 6.8,
 'summer',
 ARRAY['Tropical','Subtropical','Mediterranean / Oceanic'],
 true, 3.5,
 $$Start seeds indoors 8-10 weeks before planting out: Eggplant has a long growing season and needs a head start|Germinate at 27-30°C: Use a heat mat under seed trays — eggplant is one of the most heat-demanding seeds to germinate|Transplant when 15cm tall and temps are consistently above 20°C: Cold snaps at this stage can kill young plants|Space 60cm apart in full sun: Good spacing dramatically reduces disease problems|Stake at planting: The plant grows 60-100cm tall and becomes heavy with fruit$$,
 $$Water deeply every 4-5 days: Consistent moisture prevents bitter fruit; avoid getting leaves wet|Feed every 3 weeks with balanced fertiliser: Heavy feeder that benefits from regular nutrition throughout the season|Pinch out growing tip when 30cm tall to encourage branching and more fruit|Harvest when skin is glossy and firm: Dull skin means overripe — the flesh turns bitter and seedy|Protect from flea beetles with fine mesh: Young plants are very attractive to flea beetles$$,
 $$Flea beetle: Small holes across leaves; cover young plants with fine insect mesh|Spider mite: Fine webbing under leaves in hot, dry weather; spray with water or neem oil|Verticillium wilt: Yellowing on one side of plant; rotate crops and avoid the same bed for 3 years|Phomopsis blight: Dark lesions on fruit; remove affected fruit and improve airflow$$,
 ARRAY['Tomato','Pepper','Marigold','Basil','Thyme']),

('Fenugreek', 'Trigonella foenum-graecum',
 'Multipurpose herb-vegetable popular in Indian cooking. Leaves (methi) harvested young as greens; seeds used as spice. Extremely fast-growing and easy.',
 'novice', 25, 10, 10, 30, 18, 4, 6, 'Well-draining, moderately fertile', 6.0, 7.0,
 'winter',
 ARRAY['Subtropical','Mediterranean / Oceanic','Semi-Arid','Temperate'],
 true, 0.1,
 $$Sow seeds directly — do not transplant: Fenugreek does not like root disturbance|Broadcast seeds thickly or sow in rows 15cm apart, 1cm deep: For leaf harvest, dense sowing gives better yield|Best sown in cool weather (10-25°C): In hot climates, grow in winter; in temperate climates, grow in spring|Water in immediately after sowing: Seeds germinate in 3-5 days with warmth and moisture|Can be grown in containers as deep as 15cm: Excellent window box or balcony crop$$,
 $$Water every 3-4 days, keeping soil moist but not waterlogged|Harvest leaves when plant is 15-20cm tall: Cut the top 10cm; plant regrows for 2-3 more cuts|After the 3rd cut, allow plant to flower and set seed: Pods appear in 3-4 months; harvest when dry|No fertiliser needed for leaf crop: Fenugreek is a legume that fixes its own nitrogen|Pinch growing tips regularly to encourage bushy, leafy growth rather than tall, stemmy plants$$,
 $$Powdery mildew: Common in humid conditions; improve spacing and airflow|Root rot: From overwatering in poor-draining soil; ensure containers have drainage holes|Aphids: Occasional; spray with water|Leaf spot: Fungal spots in wet weather; reduce overhead watering$$,
 ARRAY['Fennel','Coriander','Spinach']),

-- ─── CHINESE VEGETABLES ───────────────────────────────────────────────────────

('Bok Choy', 'Brassica rapa subsp. chinensis',
 'Fast-growing Chinese cabbage with thick white stems and dark green leaves. A cool-season staple across East Asian cuisines. Very easy to grow.',
 'novice', 50, 20, 5, 24, 16, 4, 5, 'Fertile, well-draining', 6.0, 7.0,
 'spring',
 ARRAY['Temperate','Mediterranean / Oceanic','Humid Continental','Subtropical'],
 true, 0.4,
 $$Sow in cool weather: Bok choy bolts in heat — sow in early spring or autumn for best results|Sow 1cm deep in rows 30cm apart: Thin to 20cm spacing once seedlings are 5cm tall|Germination is fast — 3-7 days in cool, moist soil|Can be transplanted or direct sown: Transplants establish quickly if hardened off properly|Grows well in containers of 20cm+ depth: Great for balcony and patio gardening$$,
 $$Water every 3-4 days consistently: Bok choy is shallow-rooted and dries out quickly|Feed with nitrogen-rich fertiliser at 3 weeks: Leafy greens need nitrogen for lush growth|Harvest whole plant or outer leaves: For baby bok choy, harvest whole at 15cm; for mature, cut outer leaves|Protect from cabbage white butterfly with fine mesh: The larvae (caterpillars) devastate brassicas|Shade in late spring as temperatures rise to prevent bolting$$,
 $$Cabbage white caterpillar: Green caterpillars eating leaves; use Bt spray or hand-pick; cover with fine mesh|Aphids: Colonies in leaf joints; spray with water or insecticidal soap|Club root: Distorted, stunted roots; ensure soil pH is 6.5+ and rotate crops|Downy mildew: Yellow patches on leaves in humid conditions; improve airflow$$,
 ARRAY['Garlic','Onion','Dill','Celery','Marigold']),

('Daikon Radish', 'Raphanus sativus var. longipinnatus',
 'Large white Japanese/Chinese radish used extensively in Asian cooking. Grows very fast, breaks up compacted soil, and can be harvested as both leaf and root.',
 'novice', 60, 15, 5, 25, 15, 5, 6, 'Deep, loose, well-draining', 5.8, 6.8,
 'fall',
 ARRAY['Temperate','Mediterranean / Oceanic','Humid Continental','Subtropical'],
 false, 1.5,
 $$Sow in late summer to autumn: Daikon needs cool weather for root development; heat causes bolting|Prepare deep, loose soil: Roots can reach 40-60cm long; soil must be stone-free and deeply loosened|Sow 2cm deep, 5cm apart in rows: Thin to 15cm spacing once seedlings appear|Direct sow only — roots do not transplant: Never start in trays; always sow where they will grow|Mark rows clearly: Seedlings look like common weeds in the early stage$$,
 $$Water every 5-7 days: Consistent moisture prevents cracking and pithy texture in roots|Thin ruthlessly: Overcrowded roots become stunted; thin decisively to 15cm spacing|Harvest before a hard frost: Pull when root is 20-40cm long and 5cm diameter|Leaves are edible: Young daikon leaves make excellent stir-fry greens — harvest a few as you thin|Do not over-fertilise with nitrogen: Causes leafy growth at the expense of root development$$,
 $$Flea beetle: Small holes in seedling leaves; cover with fine mesh immediately after sowing|Cabbage fly root maggot: Tunnels in root; use fine mesh barrier at soil level|Cracking: From irregular watering; maintain consistent soil moisture|Pithy/hollow roots: Left too long in ground or grown in heat; harvest promptly$$,
 ARRAY['Carrot','Cucumber','Spinach','Lettuce','Pea']),

('Snow Peas', 'Pisum sativum var. macrocarpon',
 'Sweet, flat-podded peas eaten whole. A cool-season climber popular in Asian stir-fries. One of the most rewarding crops for effort versus yield.',
 'novice', 65, 10, 5, 24, 13, 5, 6, 'Well-draining, moderately fertile', 6.0, 7.0,
 'spring',
 ARRAY['Temperate','Mediterranean / Oceanic','Humid Continental','Subtropical'],
 false, 0.5,
 $$Sow as early as ground can be worked: Snow peas tolerate light frost — do not wait for warm weather|Set up a 120-150cm trellis or net before sowing: Peas climb by tendrils and need something to grip immediately|Sow 2-3cm deep, 10cm apart: No thinning needed; rows 45cm apart|Inoculate seeds with rhizobium before sowing: This maximises nitrogen fixation and dramatically improves yields|Do not feed with nitrogen: Peas fix atmospheric nitrogen; extra nitrogen produces leaves, not pods$$,
 $$Water every 5-7 days: Consistent moisture from flowering to harvest is critical; drought causes poor pod set|Guide tendrils onto support weekly: This prevents the plants becoming a tangled mat on the ground|Harvest when pods are flat and peas just visible: Do not let pods swell — once seeds fill out, flavour decreases|Pick every 2-3 days: Picking regularly keeps plants producing for weeks; stopping encourages plant to die off|Mulch around base after germination: Keeps soil cool and moist$$,
 $$Powdery mildew: White coating on leaves (very common in late spring); choose resistant varieties; improve airflow|Pea moth: Larvae inside pods; use fine mesh or sow early to avoid peak moth flight|Aphids: Colonies on growing tips; pinch out affected tips or spray with water|Birds: Eat germinating seeds and young shoots; protect with netting until plants are 15cm tall$$,
 ARRAY['Carrot','Spinach','Lettuce','Mint','Radish']),

('Chinese Long Beans', 'Vigna unguiculata subsp. sesquipedalis',
 'Yardlong beans popular across South and East Asia. Grow on vigorous climbing vines in hot weather. Pods reach 30-60cm long and taste similar to green beans.',
 'novice', 70, 30, 20, 38, 27, 5, 8, 'Well-draining, sandy loam', 6.0, 7.0,
 'summer',
 ARRAY['Tropical','Subtropical'],
 false, 2.0,
 $$Sow only in warm soil (20°C+): Unlike green beans, long beans are heat lovers and will not germinate in cold|Set up 180cm trellis or pole support before sowing: Vines grow very tall and need substantial support|Sow 3-4cm deep, 30cm apart at base of trellis|Do not add nitrogen fertiliser: Long beans fix their own nitrogen; extra nitrogen produces leaves only|Water in thoroughly after sowing and keep moist until germination$$,
 $$Water every 5-7 days: Once established, long beans are reasonably drought-tolerant but produce better with consistent moisture|Train vines up support: Guide the main shoot upwards weekly; side shoots will follow|Harvest pods when 30-40cm long: Pick before they start to swell and become fibrous|Harvest every 2-3 days: Plants are incredibly productive when pods are picked regularly|Feed monthly with potassium-rich fertiliser: Supports continuous pod production$$,
 $$Aphids: Common on new growth; spray with water or neem oil|Bean fly: Maggots inside stems near soil; use yellow sticky traps and remove affected plants|Powdery mildew: In humid conditions; improve airflow|Spider mite: In hot, dry weather; spray leaves with water$$,
 ARRAY['Corn','Squash','Marigold','Basil']),

-- ─── MEDITERRANEAN VEGETABLES (Spain / Italy) ─────────────────────────────────

('Artichoke', 'Cynara cardunculus var. scolymus',
 'Dramatic Mediterranean perennial producing large edible flower buds. A showpiece plant that takes a full season to establish but then produces for years.',
 'intermediate', 90, 90, 10, 32, 20, 7, 8, 'Deep, well-draining, slightly alkaline', 6.0, 6.5,
 'spring',
 ARRAY['Mediterranean / Oceanic','Subtropical','Temperate'],
 false, 6.0,
 $$Start from offshoots or transplants for faster results: Growing from seed is slow and inconsistent|Prepare very large planting holes: Mix in generous compost and ensure very deep drainage|Space plants 90cm+ apart: Artichokes grow into large architectural plants 120-150cm tall and wide|Plant in full sun in a sheltered position: Wind protection is important for the large leaves|In cold climates, mulch crowns heavily in autumn to protect from frost$$,
 $$Water weekly with deep soaking: Artichokes are thirsty; shallow watering is ineffective with their deep roots|Feed monthly with balanced fertiliser through spring and summer: These are hungry, long-season plants|Cut the central bud first: This encourages more side buds to develop|Harvest buds before they open: Tight, compact buds have the best flavour; once the scales open, they become fibrous|Cut plants back to 30cm after harvest: New growth will come from the base for next season$$,
 $$Aphids: Common in leaf bracts; spray with water or insecticidal soap; natural predators usually control them|Artichoke plume moth: Larvae burrow into buds; remove affected buds and destroy|Botrytis grey mould: In cool, damp weather; improve airflow and remove dead material|Slugs: Feed on young leaves at night; use iron phosphate pellets$$,
 ARRAY['Sunflower','Tarragon','Pea','Nasturtium']),

('Fennel', 'Foeniculum vulgare var. azoricum',
 'Florence fennel produces sweet anise-flavoured bulbs popular in Italian cooking. A beautiful, feathery plant that also attracts beneficial insects to the garden.',
 'intermediate', 75, 30, 10, 30, 20, 5, 6, 'Well-draining, moderately fertile', 6.0, 7.0,
 'spring',
 ARRAY['Mediterranean / Oceanic','Temperate','Subtropical'],
 false, 0.4,
 $$Sow directly into final position: Fennel has a long taproot and dislodges badly|Sow 1cm deep in rows 45cm apart: Thin to 30cm spacing when 10cm tall|Avoid sowing near tomatoes, peppers or beans: Fennel produces chemicals that inhibit many vegetables|Best sown in late spring for autumn harvest: Summer heat can cause bolting|Soil should be well-drained but reasonably fertile$$,
 $$Earth up the bulb as it develops: When the swelling base reaches 5cm diameter, pile soil around it (blanching) to keep it white and sweet|Water every 5-7 days: Even moisture prevents bolting; stress causes premature flowering|Harvest when bulb is 8-10cm across: Do not leave in the ground too long or it becomes woody|Cut 2cm above soil after harvest: Some varieties resprout for a second, smaller harvest|Feed once at 4 weeks with balanced fertiliser: Fennel does not need heavy feeding$$,
 $$Aphids: Common on feathery foliage; tolerate small colonies as they attract ladybirds; spray heavy infestations with water|Bolting: Premature flowering ruins the bulb; avoid heat stress and irregular watering|Slugs: Attack young seedlings; protect with copper tape or iron phosphate pellets|Root rot: From waterlogged soil; ensure excellent drainage$$,
 ARRAY['Dill','Coriander','Nasturtium']),

('Padron Pepper', 'Capsicum annuum Padrón',
 'Famous Spanish tapas pepper grown in Galicia. Small green peppers mostly mild — but 1 in 10 is fiery. Fun, productive, and delicious blistered in a pan with sea salt.',
 'novice', 75, 40, 15, 35, 24, 4, 8, 'Well-draining, moderately fertile', 6.0, 6.8,
 'summer',
 ARRAY['Mediterranean / Oceanic','Temperate','Subtropical'],
 true, 2.0,
 $$Start seeds indoors 8 weeks before last frost: Like all peppers, Padróns need a long warm season|Germinate at 25-28°C with a heat mat: Pepper seeds germinate poorly below 20°C|Transplant when nights stay above 15°C and soil is warm: Cold conditions cause permanent stunting|Space 40cm apart in full sun: Good spacing improves yield and prevents disease|Plant at same soil depth as pot — unlike tomatoes, do not bury deeper$$,
 $$Water every 3-4 days: Consistent moisture is key; drought stress increases the heat level of the peppers|Feed every 3 weeks with potassium-rich fertiliser once flowering starts: Supports continuous fruit production|Harvest when peppers are 4-6cm long, still green: Do not wait for them to turn red|Cook fresh the same day for best flavour: Blister in very hot olive oil for 2-3 minutes, serve with flaky sea salt|Leave a few to ripen red for seed saving$$,
 $$Aphids: Common on new growth; spray with neem oil or insecticidal soap|Blossom drop: Flowers falling without fruit set — caused by temperature extremes or drought|Bacterial leaf spot: Dark spots on leaves; avoid overhead watering|Verticillium wilt: Sudden wilting; no treatment — remove plant and rotate crops$$,
 ARRAY['Basil','Marigold','Onion','Carrot','Tomato']),

('Romanesco Broccoli', 'Brassica oleracea var. botrytis',
 'Stunning Italian vegetable with fractal lime-green heads. A cross between broccoli and cauliflower with a nutty, sweet flavour. A conversation piece in any garden.',
 'intermediate', 90, 50, 7, 24, 16, 5, 6, 'Rich, well-draining', 6.0, 7.0,
 'fall',
 ARRAY['Mediterranean / Oceanic','Temperate','Humid Continental'],
 false, 0.8,
 $$Start seeds indoors 6-8 weeks before transplanting: Timing is critical — aim for heads to mature in cool autumn weather|Transplant when 15cm tall and after summer heat has broken: Heat during head formation ruins Romanesco completely|Space generously at 50cm: Each plant produces one large head and needs room to develop its full rosette of leaves|Firm soil well around transplant base: Brassicas need a stable root run|Apply balanced granular fertiliser at planting and again at 4 weeks$$,
 $$Water every 5-6 days: Consistent moisture prevents hollow stems and poor head formation|Feed with nitrogen-rich fertiliser at 3 weeks after transplanting: Leaf growth now powers head development later|Protect from cabbage white butterfly with fine mesh immediately: This is the single most important pest action|Check under leaves weekly for caterpillars and egg clusters: Yellow eggs on leaf undersides hatch into devastation|Harvest when head is fully formed but before individual florets begin to open: The fractal pattern deteriorates quickly once flowering starts$$,
 $$Cabbage white caterpillar: Devastating; mandatory to use fine insect mesh or check and pick daily|Club root: Distorted roots, stunted plant; raise soil pH to 7.0+; avoid replanting brassicas for 7 years|Downy mildew: Yellow patches on leaves in cool, damp conditions; improve airflow|Aphids: In colonies along stems; spray with water or insecticidal soap$$,
 ARRAY['Celery','Onion','Dill','Marigold','Nasturtium'])

ON CONFLICT (name) DO NOTHING;
